### ISSUE TITLE
About Page Section

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#15]
Hey, so I was talking with the client about ways to introduce subtle animation. Something we wanted to play around with is animating the branding elements (the smile and tail). I made this mockup in Figma which has the svgs for everything, but the image/shape on the right are separate assets, as well as the smile. The subtle animation I was wanting to play around with was just a subtle up and down motion to add a little animation. Let me know if that makes sense and if that would be an okay thing to do elsewhere. 

Styles for page:
headline text (in the middle and in the blurb): text-4xl font-avantbold
text: text-xl font-proximasemi

For your reference, we're recreating this part of the current about page: 
![image](https://user-images.githubusercontent.com/79876365/118341290-1dc62480-b4e4-11eb-93ea-b185a5fa2f32.png)

https://www.figma.com/file/4NcynLyMr3eFfLtcVYA1Xg/Untitled?node-id=0%3A1

**Comment by ogdenstudios** [comment]
@baudoinalkali - that makes sense. It's very doable. 

I also think it makes a lot of sense to add the animation elsewhere, especially if it's connected to the smile component. Since the smile component is such a strong brand element for them, we can consider the animation to be a brand element of sorts as well. 

Thanks for the Figma file. I can take those assets and drop them into the about page, and then play around with the animation. I should have something to show you by the end of the weekend, although I'm sure we'll end up wanting to go back and forth on it a little bit between ourselves and the client. 

I'll also probably just write the animation as a specific [CSS animation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations), which will make it super portable and easy to apply wherever else we've got a similar smile SVG.

**Comment by baudoinalkali** [comment]
Sounds good, yea that is what I found for the animation, I played around with animating the tails on the divider sections which led me to think of exploring that idea further.

**Comment by ogdenstudios** [comment]
@baudoinalkali - do you want me to spend any time on the responsive styles here, or just the animation?

**Comment by baudoinalkali** [comment]
Let's go ahead and make it responsive, let's have it be text blurb, wording, then image. Also I messed around with an animation if you could just duplicate it so it's consistent, it's in the global style sheet called. Should be the only key frame.

**Comment by ogdenstudios** [comment]
@baudoinalkali - what's it called? `mover`?

**Comment by baudoinalkali** [comment]
Yes and vert-mover is the tag I have applied. You can see the intended effect on the product page.

**Comment by baudoinalkali** [comment]
Sort of related to this animation I had a question about what's possible with regards to key frames. The client floated the idea of the smile appearing when the visitor scrolls to that section then it does the animation it currently has.

**Comment by ogdenstudios** [comment]
Yeah, we can make that happen. 

The simplest way if you want to just use the CSS animation and nothing else is to just take a guess on scroll time and delay the beginning. 

But of course, that won't work most of the time. It'll just be an approximation. In order to make this happen each and every time, we probably need to write an [intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for it. We can basically have the intersection observer watch the element and make it appear as soon as a user gets there - at which point we can transition it in to the doc and also start the regular animation.

**Comment by baudoinalkali** [comment]
Do you have an idea how long something like that might take? Just want to get a sense because this is very much something that needs to be visually seen, but still in the early stages of determining the animation they want exactly, so want to gauge if it's a huge time commitment.

**Comment by ogdenstudios** [comment]
For a first pass, I would say three hours max. I was planning on wrapping the responsive pieces of this today, and I'd have time by the end of the week to get the demo on the scroll interaction. I could get you something by end of day Friday at the latest. Does that work or would you need it sooner?

**Comment by baudoinalkali** [comment]
Sounds good, let's finish this up, animation, then pricing. I'll create a separate issue for the animation.
